#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
serverDir="$root/../server"
pluginsDir="$serverDir/plugins"

mkdir -p "$serverDir" "$pluginsDir"

# Prefer user-installed jq when sudo is unavailable in WSL
if command -v jq >/dev/null 2>&1; then
  JQ="jq"
elif [[ -x "$HOME/bin/jq" ]]; then
  JQ="$HOME/bin/jq"
else
  echo "jq not found. Install to /usr/local/bin/jq or $HOME/bin/jq" >&2
  exit 1
fi

# Paper 1.12.2 (latest) via PaperMC v2 API
paperJar="$serverDir/paper-1.12.2.jar"
if [[ ! -f "$paperJar" ]]; then
  paperBuild=$(curl -s https://api.papermc.io/v2/projects/paper/versions/1.12.2 | "$JQ" -r '.builds[-1]')
  paperFile=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/1.12.2/builds/${paperBuild}" | "$JQ" -r '.downloads.application.name')
  paperUrl="https://api.papermc.io/v2/projects/paper/versions/1.12.2/builds/${paperBuild}/downloads/${paperFile}"
  curl -L "$paperUrl" -o "$paperJar"
fi

# EaglercraftXServer + EaglerWeb from GitHub releases
releaseJson=$(curl -s -H "User-Agent: eaglercraft-setup" https://api.github.com/repos/lax1dude/eaglerxserver/releases/latest)

function get_asset_url() {
  local name="$1"
  echo "$releaseJson" | "$JQ" -r ".assets[] | select(.name==\"$name\") | .browser_download_url" | head -n 1
}

eaglerServerUrl=$(get_asset_url "EaglerXServer.jar")
if [[ -z "$eaglerServerUrl" || "$eaglerServerUrl" == "null" ]]; then
  echo "EaglerXServer.jar not found in latest release assets" >&2
  exit 1
fi
curl -L "$eaglerServerUrl" -o "$pluginsDir/EaglerXServer.jar"

eaglerWebUrl=$(get_asset_url "EaglerWeb.jar")
if [[ -n "$eaglerWebUrl" && "$eaglerWebUrl" != "null" ]]; then
  curl -L "$eaglerWebUrl" -o "$pluginsDir/EaglerWeb.jar"
fi

# AuthMeReloaded from GitHub releases
authJson=$(curl -s -H "User-Agent: eaglercraft-setup" https://api.github.com/repos/AuthMe/AuthMeReloaded/releases/latest)
authUrl=$(echo "$authJson" | "$JQ" -r '.assets[] | select(.name|test("\\.jar$") and (test("sources|javadoc")|not)) | .browser_download_url' | head -n 1)
if [[ -z "$authUrl" || "$authUrl" == "null" ]]; then
  echo "AuthMeReloaded jar not found in latest release" >&2
  exit 1
fi
curl -L "$authUrl" -o "$pluginsDir/$(basename "$authUrl")"

# Ensure offline-mode for AuthMe
serverProps="$serverDir/server.properties"
if [[ ! -f "$serverProps" ]]; then
  printf "# Eaglercraft setup\nonline-mode=false\n" > "$serverProps"
else
  if grep -q '^online-mode=' "$serverProps"; then
    sed -i 's/^online-mode=.*/online-mode=false/' "$serverProps"
  else
    printf '\nonline-mode=false\n' >> "$serverProps"
  fi
fi

# Accept EULA automatically
printf "# Generated by start-all.sh\neula=true\n" > "$serverDir/eula.txt"

cd "$serverDir"
java -Xms1G -Xmx2G -jar "$paperJar" nogui
